# .pre-commit-config.yaml
# rust project pre-commit configuration
# 用法cp .pre-commit-config.yaml <your-repo> && prek install

# 设置默认安装的钩子类型
default_install_hook_types: [pre-commit, pre-push]

repos:
  - repo: local
    hooks:
      - id: fmt
        name: "cargo fmt"
        description: "Format files with cargo fmt"
        entry: cargo fmt
        language: system
        pass_filenames: false
        args: ["--"]

      - id: clippy
        name: "cargo clippy"
        description: "Lint files with cargo clippy"
        entry: cargo clippy
        language: system
        pass_filenames: false
        args:
          [
            "--all-targets",
            "--all-features",
            "--tests",
            "--benches",
            "--",
            "-D",
            "warnings",
          ]

      - id: test
        name: "cargo test"
        description: "Run tests with cargo test"
        entry: cargo nextest run
        language: system
        pass_filenames: false
        args: ["--all-features", "--", "--include-ignored"]
        stages: [pre-push] # 只在 push 时运行

      - id: build
        name: "cargo build"
        description: "Build project with cargo build"
        entry: cargo build
        language: system
        pass_filenames: false
        args: ["--locked"]
        stages: [pre-push] # 只在 push 时运行

      - id: check
        name: "cargo check"
        description: "Check project with cargo check"
        entry: cargo check
        language: system
        pass_filenames: false
        args: ["--all"]
        stages: [pre-push] # 只在 push 时运行
